### ISSUE TITLE
Incorrect block time

### ISSUE THREAD

**Issue by egyptianbman** [Snowgem/snowgem-pool#1]
https://github.com/Snowgem/snowgem-pool/blob/bd72d581b850c5ff8f7c5d9350cb3143bc5e913e/website/static/miner_stats.js#L150

Due to this line (as well as others), Luck estimates will be incorrect.

**Comment by TENTOfficial** [comment]
thank you. It was fixed [here](https://github.com/Snowgem/snowgem-pool/commit/743f9e018bb1095287746a84029c21b31ab9518f)
